Repository MEZOZIDA/medidoc, pull requests merged in 2024-04, with the labels that each got.

#14 자가진단 페이지 : component UI 구성, DB에서 의심되는 질환 정보 가져오기 완료
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  src/api/supabase.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/selftest/page.tsx
  src/app/selftestresult/[resultId]/page.tsx
  src/app/selftestresult/page.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/shared/zustand/selftestStore.ts
  src/types/index.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능 구현

#16 Feat/apply 컴포넌트 이동/ 날짜 기능구현중
  package.json
  src/app/apply/page.tsx
  src/components/apply/ApplyPageFourth.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThird.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/CourseSelectItem.tsx
  src/components/apply/DateSelect.tsx
  src/components/apply/GetNewDate.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/Reservation.tsx
  src/components/apply/TimeSelect.tsx
  src/components/apply/VisitorInfo.tsx
  src/shared/zustand/applyStore.ts
  yarn.lock
Labels: 기능 구현, 도움이 필요함

#17 병원정보 출력 페이지 컴포넌트 구현(1차)
  src/app/layout.tsx
  src/app/map/[hospitalId]/page.tsx
  src/app/map/page.tsx
  src/components/map/BottomList.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/HospitalMainInfo.tsx
  src/components/map/HospitalTopInfo.tsx
  src/components/map/Notice.tsx
  src/components/map/defaultTab/DefaultTab.tsx
  src/components/map/defaultTab/Notice.tsx
  src/components/map/defaultTab/ProgramInfo.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/programInfo/Course.tsx
  src/components/map/programInfo/ProgramInfo.tsx
  src/components/map/programInfo/ProgramPrice.tsx
  src/components/map/review/VisitorReviewItem.tsx
  src/components/map/review/VisitorReviewList.tsx
  src/components/map/reviewImage/VisitorReviewImageItem.tsx
  src/components/map/reviewImage/VisitorReviewImageList.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/shared/zustand/detailTabStore.ts
  src/types/index.ts
  yarn.lock
Labels: 기능 구현, 파일 수정

#18 로그인 페이지 : 카카오 로그인, 구글 로그인 구현
  package.json
  src/app/auth/callback/route.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/supabaseProvider.tsx
  src/components/layout/Navbar.tsx
  src/shared/zustand/authStore.ts
  src/shared/zustand/selftestStore.ts
  yarn.lock
Labels: 기능 구현

#20 Prettier 미적용 문제 해결
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: 문제 해결, 파일 수정

#28 유효성 검사, 날짜 & 시간 예약 및 현재 시간에 따른 예약 비활성화 구현완료
  src/app/apply/page.tsx
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/DateSelect.tsx
  src/components/apply/GetNewDate.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/Reservation.tsx
  src/components/apply/TimeSelect.tsx
  src/components/apply/VisitorInfo.tsx
  src/shared/zustand/applyStore.ts
  src/types/index.ts
Labels: 기능 구현

#29 Feat/consult 기능 구현
  .vscode/settings.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswer.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultImages.tsx
  src/components/consult/ConsultItem.tsx
  src/components/consult/ConsultQuestion.tsx
  src/components/consult/ConsultTabs.tsx
  src/types/index.ts
Labels: 문제 해결, 기능 구현, 파일 수정

#30 자가진단페이지 : 증상 임의 선택 시 질환 결과 출력 구현
  src/app/selftest/page.tsx
  src/components/selftest/BodyParts.tsx
  src/components/selftest/Departments.tsx
  src/components/selftest/Genders.tsx
  src/components/selftest/Symptoms.tsx
  src/components/selftest/TestResult.tsx
  src/shared/zustand/selftestStore.ts
  src/types/supabase.ts
Labels: 기능 구현, 파일 수정

#31 로그인 페이지 : 로그인 기능 구현
  package.json
  src/api/supabase.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/provider.tsx
  src/app/providers.tsx
  src/app/supabaseProvider.tsx
  src/hooks/clientSession.ts
  src/shared/zustand/authStore.ts
  yarn.lock
Labels: 기능 구현, 파일 수정

#33 [!HOTFIX/#32] - 병원정보 페이지 TabState 복구
  src/types/index.ts
Labels: 문제 해결, 파일 수정

#39 마이페이지 UI 및 DB 연동 진행 중
  next.config.mjs
  package.json
  src/app/mypage/[userId]/page.tsx
  src/components/layout/Navbar.tsx
  src/components/mypage/AccessDenied.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/MyQuestionList.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ReservationInfoList.tsx
  src/components/mypage/ScrappedList.tsx
  src/components/selftest/Symptoms.tsx
  src/types/index.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능 구현

#40 answer form 추가
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswer.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultImages.tsx
  src/components/consult/ConsultItem.tsx
  src/components/consult/ConsultQuestion.tsx
  src/types/supabase.ts
Labels: 기능 구현

#41 병원정보 DB 데이터 출력 구현
  src/app/map/[hospitalId]/page.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/hospitalList/HospitalItem.tsx
  src/components/map/hospitalList/HospitalList.tsx
  src/hooks/getHospitalData.ts
  src/utils/changeTimeFormat.ts
  src/utils/checkHospitalOpen.ts
Labels: 기능 구현

#46 Review 관련 폴더 생성 및 세분화
  .vscode/settings.json
  package.json
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/hospital/page.tsx
  src/app/hospital/reviewform/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultImages.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/review/ReviewHeader.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRating.tsx
  src/components/map/review/Reviews.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/types/index.ts
  yarn.lock
Labels: 기능 구현, 파일 수정

#47 마이페이지 예약리스트 UI 구현
  src/app/login/page.tsx
  src/app/mypage/[userId]/page.tsx
  src/components/layout/Navbar.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/shared/zustand/myPageStore.ts
  src/types/index.ts
  src/types/supabase.ts
  tailwind.config.ts
Labels: 문제 해결, 기능 구현

#48 인적사항 검진코스 날짜 시간 예약 및 보여주기 (DB통신) 구현
  src/api/supabase.ts
  src/app/login/page.tsx
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/CourseSelectItem.tsx
  src/components/apply/HospitalName.tsx
  src/components/apply/Reservation.tsx
  src/components/apply/TimeSelect.tsx
  src/components/apply/VisitorInfo.tsx
  src/components/consult/ConsultTabs.tsx
  src/components/layout/Navbar.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/hooks/getReservationData.ts
  src/shared/zustand/applyStore.ts
  src/types/supabase.ts
  src/utils/changeTimeFormat.ts
Labels: 문제 해결, 기능 구현, 파일 수정

#50 병원 상세페이지 카카오 지도 연동 & 로그인 로직 수정
  src/app/login/page.tsx
  src/components/map/HospitalInfoHeader.tsx
  src/components/map/Map.tsx
  src/utils/drawKakaoMap.ts
Labels: 기능 구현, 파일 수정

#52 Feat/apply - 유효성 검사, 기본 퍼블리싱 작업
  src/app/globals.css
  src/components/apply/ApplyPageFour.tsx
  src/components/apply/ApplyPageOne.tsx
  src/components/apply/ApplyPageThree.tsx
  src/components/apply/ApplyPageTwo.tsx
  src/components/apply/CalendarDay.tsx
  src/components/apply/CourseSelect.tsx
  src/components/apply/TimeSelect.tsx
  src/components/layout/Navbar.tsx
  src/shared/zustand/applyStore.ts
Labels: 문제 해결, 기능 구현

#53 마이페이지 : 스크랩 리스트, 예약 리스트, 실시간 상담 리스트 등 구현 완료
  src/components/layout/Navbar.tsx
  src/components/mypage/AdminMenu.tsx
  src/components/mypage/AdminQuestionItem.tsx
  src/components/mypage/MyQuestionItem.tsx
  src/components/mypage/MyQuestionList.tsx
  src/components/mypage/ReservationInfoItem.tsx
  src/components/mypage/ScrappedList.tsx
  src/hooks/getMyConsultData.ts
  src/types/index.ts
  src/types/supabase.ts
Labels: 문제 해결, 기능 구현

#55 Review 생성 및 구현 완료
  src/api/supabase.ts
  src/app/consult/[consultId]/page.tsx
  src/app/consult/page.tsx
  src/app/hospital/page.tsx
  src/app/hospital/review/page.tsx
  src/app/hospital/reviewform/page.tsx
  src/app/login/page.tsx
  src/components/consult/AnswerForm.tsx
  src/components/consult/AskForm.tsx
  src/components/consult/ConsultAnswerForm.tsx
  src/components/consult/ConsultNotice.tsx
  src/components/layout/Navbar.tsx
  src/components/map/defaultTab/ReviewImageList.tsx
  src/components/map/defaultTab/ReviewList.tsx
  src/components/map/imageTab/ImageTab.tsx
  src/components/map/review/ReviewForm.tsx
  src/components/map/review/ReviewHeader.tsx
  src/components/map/review/ReviewItem.tsx
  src/components/map/review/ReviewRecent.tsx
  src/components/map/review/ReviewTags.tsx
  src/components/map/review/Reviews.tsx
  src/components/map/reviewTab/ReviewTab.tsx
  src/types/index.ts
  src/utils/hashtag.tsx
Labels: 기능 구현, 파일 수정
